### ISSUE TITLE
get 404 error when object name contains space

### ISSUE THREAD

**Issue by mohgh** [nginxinc/nginx-s3-gateway#30] opened 2022-04-14 14:36 UTC
When the object name contains space, the browser converts the spaces with %20 and returns 404 however the file exists in s3 storage.

**Comment by dekobon** [comment] 2022-04-20 18:09
Does the problem reproduce when you use this container image: https://github.com/nginxinc/nginx-s3-gateway/pkgs/container/nginx-s3-gateway%2Fnginx-oss-s3-gateway/19023051?tag=latest-njs-oss-20220413

**Comment by dekobon** [comment] 2022-05-17 20:02
The branch referenced above has been merged into master. Please check to see if it reproduces with the latest code.

**Comment by dekobon** [comment] 2022-08-03 18:36
I'm closing this issue because I have not got an update. Please comment or reopen if this is in error.

**Closed by dekobon** 2022-08-03 18:36 UTC
